import { GoogleGenAI, Type } from "@google/genai";

const journalEntrySchema = {
    type: Type.OBJECT,
    properties: {
        reflection: {
            type: Type.ARRAY,
            description: "A list of [5-10] points of the day, which includes the most important events, feelings, people and thoughts that the user had during the day",
            items: {
                type: Type.STRING
            }
        },
        gemini_response: {
            type: Type.OBJECT,
            description: "The response generated by analysing the journal entry, which includes the calmness score, anxious score, productivity score, sadness score and happiness score for the day",
            properties: {
                calmness_score: {
                    type: Type.NUMBER,
                    description: "The calmness score for the day"
                },
                anxious_score: {
                    type: Type.NUMBER,
                    description: "The anxious score for the day"
                },
                productivity_score: {
                    type: Type.NUMBER,
                    description: "The productivity score for the day"
                },
                sadness_score: {
                    type: Type.NUMBER,
                    description: "The sadness score for the day"
                },
                happiness_score: {
                    type: Type.NUMBER,
                    description: "The happiness score for the day"
                }
            },
            required: ["calmness_score", "anxious_score", "productivity_score", "sadness_score", "happiness_score"]
        }

    },
    required: ["reflection", "gemini_response"]
}

const insightsSchema = {
    type: Type.OBJECT,
    properties: {
        observations: {
            type: Type.ARRAY,
            description: "A list of exactly 4 personalized observations about the user's journaling patterns.",
            items: {
                type: Type.OBJECT,
                properties: {
                    text: {
                        type: Type.STRING,
                        description: "The worded observation referencing patterns or correlations (e.g., 'You consistently feel energetic on weekends...')"
                    },
                    tag: {
                        type: Type.STRING,
                        description: "A single distinct word categorization tag like 'Pattern', 'Insight', 'Correlation', or 'Rhythm'"
                    }
                },
                required: ["text", "tag"]
            }
        },
        advices: {
            type: Type.ARRAY,
            description: "A list of exactly 4 highly personalized productivity or wellness advice based on the entries pattern.",
            items: {
                type: Type.OBJECT,
                properties: {
                    category: { type: Type.STRING, description: "A simple tag like 'Timing', 'Energy', 'Focus', 'Rest'" },
                    title: { type: Type.STRING, description: "A concise 3-4 word title, e.g. 'Write before 9am'" },
                    body: { type: Type.STRING, description: "A 1-2 sentence explanation of the pattern driving this advice." },
                    action: { type: Type.STRING, description: "A highly actionable 2-3 word button label, e.g. 'Set reminder'" },
                    icon: { type: Type.STRING, description: "A single emoji representing the advice" },
                    color: { type: Type.STRING, description: "Pick one: 'var(--primary)', 'var(--secondary)', 'var(--accent-green)', 'var(--accent-amber)', 'var(--accent-rose)'" }
                },
                required: ["category", "title", "body", "action", "icon", "color"]
            }
        },
        themes: {
            type: Type.ARRAY,
            description: "A list of 8-10 recurring free-form themes, topics, or emotional narratives found across the entries.",
            items: {
                type: Type.OBJECT,
                properties: {
                    label: { type: Type.STRING, description: "The theme name, e.g. 'Morning Anxiety', 'Coffee Rituals', 'Project Deadlines'" },
                    size: { type: Type.STRING, enum: ["sm", "md", "lg", "xl"], description: "Relative importance/frequency of the theme" },
                    color: { type: Type.STRING, description: "A CSS variable: 'var(--primary)', 'var(--secondary)', 'var(--accent-green)', 'var(--accent-amber)', 'var(--accent-rose)'" },
                    freq: { type: Type.NUMBER, description: "Number of entries this theme appeared in" }
                },
                required: ["label", "size", "color", "freq"]
            }
        }
    },
    required: ["observations", "advices", "themes"]
}


async function generateJournalReport({ chat }) {

    const ai = new GoogleGenAI({
        apiKey: process.env.GOOGLE_GENAI_API_KEY,
    });

    const prompt = `Analyze the following journal entry and provide a structured response:\n\n${chat}`;

    const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-lite-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: journalEntrySchema,
        }
    });

    const result = JSON.parse(response.text);

    return result;

};

async function generateGlobalInsights({ entriesText }) {
    const ai = new GoogleGenAI({
        apiKey: process.env.GOOGLE_GENAI_API_KEY,
    });

    const prompt = `Act as an expert psychological and productivity analyst. Analyze the following sequence of the user's last 15 journal entries. 
Provide exactly 4 high-level observations, exactly 4 actionable productivity/wellness advices, and 8-10 recurring free-form themes. Look for multi-day aggregate trends, recurring narratives, hidden emotional loops, or behavioral rhythms. Do not summarize individual days; focus on the "big picture" of who this person is and how their patterns correlate with their outcomes. Themes should be specific and free-form based on their actual content.\n\n${entriesText}`;

    const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-lite-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: insightsSchema,
        }
    });

    return JSON.parse(response.text);
}


export default generateJournalReport;
export { generateGlobalInsights };
